### PR TITLE
Api key generation function and middleware validation

### PR DESCRIPTION
**Pull request by Tu-Code**
Completed issues #2 and #7

### CODE REVIEW

**Comment by Alfred-Onuada** [comment]
Thanks, @Tu-Code, I didn't get a notification from Github on this, that's why I am just seeing it today 😣, Nice work. I'll fix a date so we can all with @tecnosam review and then get this PR approved.

**Comment by Alfred-Onuada** [comment]
Also move this tasks into the "In Review" column on the github projects

**Comment by Alfred-Onuada** [comment]
@Tu-Code can you change the PR to merge into dev please, thanks

**Comment by Tu-Code** [comment]
I tried but it’s saying there’s no difference between the branches and
can’t create the PR. I apologize for the late response. I’m trying to lint
my code now but I’m facing some version issues, I’ll send a PR then to see
if it works once I’ve updated it.

**Comment by Tu-Code** [comment]
I've sent the PR to dev and linted my code, @Alfred-Onuada.

**Pull request merged**
